# Generated by Django 3.1.6 on 2021-06-14 14:46
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255, verbose_name='Name of the website')),
                ('username', models.CharField(max_length=255, verbose_name='Username used to log in')),
                ('password', models.CharField(max_length=255, verbose_name='Password used to log in')),
            ],
        ),
    ]
