# Generated by Django 3.1.6 on 2021-06-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_passwordstore_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordstore',
            name='password',
        ),
    ]
