# Generated by Django 3.1.6 on 2021-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_remove_passwordstore_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordstore',
            name='password',
            field=models.CharField(default='asd', max_length=255, verbose_name='Password used to log in'),
            preserve_default=False,
        ),
    ]
