# Generated by Django 3.1.6 on 2021-06-14 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_passwordstore_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordstore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='passwordstore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 14, 17, 37, 37, 459864, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
