# Generated by Django 3.1.6 on 2021-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210611_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bussy',
            field=models.BooleanField(default=False),
        ),
    ]
