# Generated by Django 3.1.6 on 2021-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_bussy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='longer_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
