# Generated by Django 3.1.6 on 2021-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210612_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
