# Generated by Django 3.1.6 on 2021-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210612_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.BooleanField(default=True),
        ),
    ]
