# Generated by Django 3.1.6 on 2021-06-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210612_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
