# Generated by Django 3.1.6 on 2021-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='child',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_event_day',
            field=models.BooleanField(default=False),
        ),
    ]
