# Generated by Django 3.1.5 on 2021-01-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210128_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
