# Generated by Django 3.1.5 on 2021-01-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210130_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(default='------', max_length=150),
        ),
    ]
