# Generated by Django 3.1.5 on 2021-01-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_entry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.CharField(default='------', max_length=100),
        ),
    ]
