# Generated by Django 3.1.6 on 2021-02-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210131_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='set_minutes',
            field=models.IntegerField(default=300),
        ),
    ]
