# Generated by Django 3.1.6 on 2021-02-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_entry_set_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='set_minutes',
            field=models.IntegerField(default=5),
        ),
    ]
