# Generated by Django 3.1.6 on 2021-02-26 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20210226_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 17, 16, 19, 11241)),
        ),
    ]
