# Generated by Django 3.1.5 on 2021-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_invitation_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_ceo',
            field=models.BooleanField(default=False),
        ),
    ]
