# Generated by Django 3.1.6 on 2021-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_invitation_is_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=22),
        ),
    ]
