# Generated by Django 3.1.6 on 2021-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationkey',
            name='key',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
