# Generated by Django 3.1.5 on 2021-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210127_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
