# Generated by Django 3.1.6 on 2021-05-12 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20210512_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0005_userprofile_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.authenticationkey')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
